config/routes.rb
Brasil2014::Application.routes.draw do
  resources :album, only: :index

  root 'home#index'

end

app/models/country.rb
class Country
	include HTTParty
	base_uri Rails.configuration.panini_url

	def self.find_all
		options = { query: {token: "s3cr3t"} }
		get("/countries.json", options)
	end
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
  def index
  	@countries = Country.find_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/album/index.html.haml
%h1 ALBUM PANINI
%p Listado de Paises con sus jugadores

- if @countries.instance_of?(Array)
  %table{ border: "1"}
    %tr
      %th Nombre
      %th Posicion
      %th email
      %th Jugadores
    - @countries.each do |country|
      %tr
        %td= country["name"]
        %td= country["position"]
        %td= country["email"]
        %td
          - if country["players"].any?
            %table{ border: "1"}
              %tr
                %th # Vista
                %th Nombre
                %th Team
              - country["players"].each do |player|
                %tr
                  %td= player["number"]
                  %td= player["name"]
                  %td= player["team"]
          - else
            No tiene Jugadores
- else
  %strong
    %em Error al sacar los datos del Web Service
    = @countries

app/views/home/index.html.haml
%h1 BRASIL 2014
%p= link_to "ALBUM", album_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brasil2014</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>